### ISSUE TITLE
Building Network stuck at 0%

### ISSUE THREAD

**Issue by Goeffus** [Metaboverse/Metaboverse#113]
Hello all,
I tried using Metaboverse to combine Proteomics and Metabolomics data of mouse livers. I think I formatted the data correctly, but when I start building a network, it is stuck at 0% permanently.
Is it necessary to put in all 3 types of OMICs? I have fold change and p-value for both experiments in a classic WT vs KO approach. Is it enough to just put in Default (2-condition)? When formatting the tables I see that fold change and p-Value are not mapped properly, is this the problem? Do I have to provide a table with 5+5 (WT+DKO) values or can I put in pre calculated p-value and fold changes?

Thanks in advance and best wishes!

**Comment by j-berg** [comment]
Hi @Goeffus, thanks for reaching out! 

It sounds like there is likely an issue in launching the backend executable that is curating the network for Metaboverse. Could you let me know what version you are using and which operating system? Also, do you receive a `metaboverse_session_...` file in your output location?

Feel free to email me your data tables @ jordan<dot>berg<at>biochem.utah.edu if you would like me to dig a little further or double-check the formatting of your input files.

**Comment by j-berg** [comment]
Not a problem, glad you reached out! I will double-check the links through the Rutter lab website and check that they are functioning consistently.

Please let me know if you run into any other issues or questions - happy to help! I'll close this issue for now, but feel free to re-open if the issue comes back.
