### ISSUE TITLE
SyntaxError: unexpected EOF while parsing

### ISSUE THREAD

**Issue by jitugeorge** [Metaboverse/Metaboverse#130]
Hi,

I was trying to use transcript and metabolomics data and got this error message "SyntaxError: unexpected EOF while parsing" [2952] Failed to execute script '__main__' due to unhandled exception!. Could you please help me understand what I might be doing wrong.

Thank you!

**Comment by j-berg** [comment]
Hi - thanks for reaching out and for the error details. This is likely linked to some unexpected character encountered in the file. Would you mind connected via my email, jordanberg.contact@gmail.com, where you can share the files and I can take a closer look at their formatting?

**Comment by j-berg** [comment]
Fixes scheduled for Metaboverse v0.10.2
