### ISSUE TITLE
Metaboverse issue

### ISSUE THREAD

**Issue by prajishiyer** [Metaboverse/Metaboverse#131]
Hello Metaboverse team,

I am trying to run the metaboverse in my mac. I have my own metabolomics data which I formated as per the software. But I am getting attribute error float object has no attribute lsstrip. I checked in the documentation for that error. There is no white space in my file since I formated that using metaboverse. Then why I am getting that error and how I can solve it.

I tried running one of your test samples. It does run 100%. So installation is OK. But I don't know whats the problem with my samples.

**Comment by j-berg** [comment]
Hi @prajishiyer - thanks for reaching out and providing details on the error you are experiencing. Could you provide any error or log files that are output? You could upload here, or email them to me directly at jordanberg.contact@gmail.com

**Comment by j-berg** [comment]
Formatting checks implemented with https://github.com/Metaboverse/metaboverse-cli/commit/4db9337c5a70c4e70806008bf047510e9e58d576 should assist in this issue. Will be included with Metaboverse v0.11.0, which I am planning on releasing in the next few days. Closing issue for now.
