### ISSUE TITLE
Nearest Neighbor Capacity

### ISSUE THREAD

**Issue by ig-ghub** [Metaboverse/Metaboverse#14]
**Is your feature request related to a problem? Please describe.**
It's not immediately apparent when increasing the Nearest Neighbor number that max capacity has been exceeded. So you increase the number but nothing seems to happen, and no easy-to-see feedback.

**Describe the solution you'd like**
Increase the visibility of the warning message to let the user know that Nearest Neighbor max capacity has been exceeded, and possibly include a message that more neighbors could be calculated on a more powerful machine if the program takes that into account.

**Describe alternatives you've considered**
On tool startup, update users with systems beneath/at the minimum requirements that certain features like Nearest Neighbor adjustment may be limited or disabled due to system specs.

**Additional context**

**Comment by j-berg** [comment]
Does an alert box pop up when you exceed the NN's? I guess it is difficult to know kNN network to network which will exceed plotting capacity. Maybe display a pop-up when they enter higher kNN values to warn them that performance might be compromised? I like the idea of a warning earlier that will alert them if there systems  reqs are not sufficient.

**Comment by j-berg** [comment]
This has been addressed in a previous update to provide an alert box when NN capacity has been exceeded. Should be available from v0.1.4b onward (at the least).
