### ISSUE TITLE
Expression value

### ISSUE THREAD

**Issue by SarahSt23** [Metaboverse/Metaboverse#146]
Hi,
Really great plateform and super user friendly compare to the other one out there !
I have this bug when I input metabolomic and transcriptomic data. I cannot have the expression value on the figure. 
![image](https://github.com/Metaboverse/Metaboverse/assets/143652036/1d11ff98-1c9c-4412-9cd7-495549d62f52)
Here are the two files I input and the session data 
[rna metaverse_unmapped.txt](https://github.com/Metaboverse/Metaboverse/files/12480091/rna.metaverse_unmapped.txt)
[lcms metaverse 2.txt](https://github.com/Metaboverse/Metaboverse/files/12480096/lcms.metaverse.2.txt)
![image](https://github.com/Metaboverse/Metaboverse/assets/143652036/385feaa8-be32-4e9e-bf6a-07b32934545d)

Thanks in advance for the help.
Sarah

**Comment by j-berg** [comment]
Hi Sarah,

Thanks for reaching out, and thank you for providing the details. I am a
bit behind right now, but will put this on my to-do list for next week as
soon as I am able and see what I can figure out. Talk soon!

Jordan

**Comment by j-berg** [comment]
Sorry it's taking me longer to address this issue than I hoped. In a partial answer to the bug you encountered, I think there is an issue with the metabolite synonym matching. The MetaboAnalyst API was down a while ago and so I disabled this partially, so I will need to look at this and make sure the way Metaboverse is communicating with their API is up-to-date (see #144). It looks like Metaboverse - based on the Reactome database - is looking for transcript IDs, Uniprot IDs, or common gene names when mapping gene measurements to the network. I need to take a closer look at this and figure out a better solution. Hoping to get to this soon! I'll keep you updated as I am able. Thank you for your patience!

**Comment by j-berg** [comment]
For now I am going to just add a note about needing to use Ensembl transcript IDs over gene IDs (49aedfcdc183ef31d89ed3542ef702ff61522a7b), but in general Ensembl gene names are likely the safest approach for mapping gene expression data to the network. I want to generate a more robust solution in the future, but at least for now don't have the bandwidth to address this particular issue right now. Sorry
