### ISSUE TITLE
Unable to Run Test Data 

### ISSUE THREAD

**Issue by bhlam00** [Metaboverse/Metaboverse#150]
I'm fairly new to analyzing metabolomics data and am trying to go through some of the test data; however, at around 50%, I get an error. I've tried changing the file type, but this doesn't work as well. Would appreciate any advice on this and how to get the results. 
<img width="927" alt="Screenshot 2023-10-18 at 9 09 05 PM" src="https://github.com/Metaboverse/Metaboverse/assets/148405274/fec11153-21d3-4b5b-b262-195bdca95b1e">

**Comment by j-berg** [comment]
Hi @bhlam00, thanks for raising this - I will look into this this weekend and get back to you.

**Comment by bhlam00** [comment]
Just to update - I was able to run the test data, but still get this error when trying to run my own. Initially I was getting this regardless of the dataset (mine and test data)

**Comment by j-berg** [comment]
I see - based on the error you are receiving, I am guessing there is an unrecognized character in one of your entity names (row names). You could take a quick look, or I am happy to look as well. If you feel comfortable sharing the data, you can email me here: jordanberg.contact@gmail.com

Could you also let me know what version of Metaboverse you are using, and share any complete log files you receive. In [v0.11.0](https://github.com/Metaboverse/Metaboverse/releases/tag/v0.11.0), we added additional logging to try and return problematic input data rows to help narrow in any anything strange.

**Comment by bhlam00** [comment]
Ah, thanks for letting me know! I fixed the names and was able to get it to run!

**Comment by j-berg** [comment]
Glad that worked!
