### ISSUE TITLE
Stucked on "curation complete... file loaded"  

### ISSUE THREAD

**Issue by yeast1234** [Metaboverse/Metaboverse#155]
Hey,
I tried to use the metaboverse app in Windows by using a transcriptomics and metabolomics dataset. It seems all works so far but I get at the end stucked at the point "curation complete... loading file". I tried the App with your test data before and that worked...

What could be the issue here? Would be great if you could help me :) thanks in advance!

This is what I get in the .log  file:
Checking Transcriptomics data conversion:
    None
Checking Metabolomics data conversion:
    None
Data processed of dimensions: (372, 1)
Preparing metadata...
Preparing references...
Reading metabolite mapper...
Building network...
Compiling super pathways...
Compiling network degree database...
Exporting template...
Graphing complete.
Successfully loaded network with 8398 nodes and 21005 edges
Generating Metaboverse neighbors dictionary for organism...
Tuning neighbors dictionary...
Writing neighbors dictionary to database file...
Modeling data onto network...
Post-processing graph metadata...
Mapping user data...
Mapping data onto network...
Input data dimensions: (372, 1)
Pre-processed data dimensions: (372, 1)
Outputting unmapped metabolomics values (if any exist)...
	- Outputting 0 unmapped metabolites for reference.
Broadcasting values where available...
Compiling collapsed reaction reference...
Collapse match threshold: 0.3
Degree threshold for collapsing: 30.0
Analyzing 1635 reactions for collapsing...
Exporting graph...
Graphing complete.

########
STDERR:
########
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  191M    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  191M    0 1104k    0     0   656k      0  0:04:58  0:00:01  0:04:57  657k
  2  191M    2 5680k    0     0  2111k      0  0:01:32  0:00:02  0:01:30 2113k
  5  191M    5 10.7M    0     0  3005k      0  0:01:05  0:00:03  0:01:02 3007k
  8  191M    8 17.0M    0     0  3724k      0  0:00:52  0:00:04  0:00:48 3726k
 12  191M   12 22.9M    0     0  4142k      0  0:00:47  0:00:05  0:00:42 4728k
 15  191M   15 29.1M    0     0  4470k      0  0:00:43  0:00:06  0:00:37 5753k
 18  191M   18 35.5M    0     0  4739k      0  0:00:41  0:00:07  0:00:34 6157k
 21  191M   21 41.4M    0     0  4891k      0  0:00:40  0:00:08  0:00:32 6279k
 24  191M   24 47.0M    0     0  4979k      0  0:00:39  0:00:09  0:00:30 6153k
 27  191M   27 51.8M    0     0  4972k      0  0:00:39  0:00:10  0:00:29 5915k
 29  191M   29 56.6M    0     0  4966k      0  0:00:39  0:00:11  0:00:28 5628k
 32  191M   32 62.2M    0     0  5023k      0  0:00:39  0:00:12  0:00:27 5457k
 35  191M   35 67.4M    0     0  5049k      0  0:00:38  0:00:13  0:00:25 5323k
 38  191M   38 73.0M    0     0  5096k      0  0:00:38  0:00:14  0:00:24 5321k
 40  191M   40 78.0M    0     0  5100k      0  0:00:38  0:00:15  0:00:23 5372k
 43  191M   43 83.3M    0     0  5117k      0  0:00:38  0:00:16  0:00:22 5472k
 46  191M   46 89.3M    0     0  5175k      0  0:00:37  0:00:17  0:00:20 5561k
 49  191M   49 95.4M    0     0  5234k      0  0:00:37  0:00:18  0:00:19 5740k
 52  191M   52  100M    0     0  5249k      0  0:00:37  0:00:19  0:00:18 5699k
 56  191M   56  107M    0     0  5308k      0  0:00:36  0:00:20  0:00:16 5960k
 59  191M   59  113M    0     0  5367k      0  0:00:36  0:00:21  0:00:15 6201k
 62  191M   62  118M    0     0  5369k      0  0:00:36  0:00:22  0:00:14 6054k
 65  191M   65  124M    0     0  5404k      0  0:00:36  0:00:23  0:00:13 6039k
 68  191M   68  130M    0     0  5408k      0  0:00:36  0:00:24  0:00:12 6033k
 70  191M   70  135M    0     0  5415k      0  0:00:36  0:00:25  0:00:11 5859k
 73  191M   73  140M    0     0  5405k      0  0:00:36  0:00:26  0:00:10 5572k
 76  191M   76  146M    0     0  5405k      0  0:00:36  0:00:27  0:00:09 5572k
 79  191M   79  151M    0     0  5403k      0  0:00:36  0:00:28  0:00:08 5399k
 81  191M   81  154M    0     0  5346k      0  0:00:36  0:00:29  0:00:07 5040k
 83  191M   83  159M    0     0  5321k      0  0:00:36  0:00:30  0:00:06 4838k
 86  191M   86  164M    0     0  5322k      0  0:00:36  0:00:31  0:00:05 4878k
 89  191M   89  170M    0     0  5335k      0  0:00:36  0:00:32  0:00:04 4947k
 91  191M   91  175M    0     0  5339k      0  0:00:36  0:00:33  0:00:03 4977k
 94  191M   94  181M    0     0  5354k      0  0:00:36  0:00:34  0:00:02 5407k
 97  191M   97  187M    0     0  5375k      0  0:00:36  0:00:35  0:00:01 5705k
100  191M  100  191M    0     0  5379k      0  0:00:36  0:00:36 --:--:-- 5757k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  1 54.4M    1  864k    0     0   713k      0  0:01:18  0:00:01  0:01:17  716k
 10 54.4M   10 5984k    0     0  2711k      0  0:00:20  0:00:02  0:00:18 2717k
 17 54.4M   17 9936k    0     0  3080k      0  0:00:18  0:00:03  0:00:15 3084k
 23 54.4M   23 12.9M    0     0  3158k      0  0:00:17  0:00:04  0:00:13 3161k
 31 54.4M   31 16.9M    0     0  3315k      0  0:00:16  0:00:05  0:00:11 3496k
 37 54.4M   37 20.3M    0     0  3361k      0  0:00:16  0:00:06  0:00:10 4003k
 43 54.4M   43 23.9M    0     0  3395k      0  0:00:16  0:00:07  0:00:09 3697k
 50 54.4M   50 27.7M    0     0  3458k      0  0:00:16  0:00:08  0:00:08 3702k
 57 54.4M   57 31.5M    0     0  3501k      0  0:00:15  0:00:09  0:00:06 3789k
 65 54.4M   65 35.9M    0     0  3597k      0  0:00:15  0:00:10  0:00:05 3892k
 73 54.4M   73 39.9M    0     0  3646k      0  0:00:15  0:00:11  0:00:04 4000k
 80 54.4M   80 43.6M    0     0  3658k      0  0:00:15  0:00:12  0:00:03 4036k
 86 54.4M   86 47.2M    0     0  3663k      0  0:00:15  0:00:13  0:00:02 3999k
 93 54.4M   93 50.8M    0     0  3662k      0  0:00:15  0:00:14  0:00:01 3959k
100 54.4M  100 54.4M    0     0  3736k      0  0:00:14  0:00:14 --:--:-- 4040k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 6889k    0 55380    0     0  77893      0  0:01:30 --:--:--  0:01:30 78220
 69 6889k   69 4771k    0     0  2822k      0  0:00:02  0:00:01  0:00:01 2828k
100 6889k  100 6889k    0     0  3143k      0  0:00:02  0:00:02 --:--:-- 3150k
pandas\core\series.py:1028: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  3 3013k    3 98304    0     0   116k      0  0:00:25 --:--:--  0:00:25  116k
 73 3013k   73 2208k    0     0  1254k      0  0:00:02  0:00:01  0:00:01 1255k
100 3013k  100 3013k    0     0  1579k      0  0:00:01  0:00:01 --:--:-- 1581k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  9  982k    9 98304    0     0   120k      0  0:00:08 --:--:--  0:00:08  121k
100  982k  100  982k    0     0   801k      0  0:00:01  0:00:01 --:--:--  803k
pandas\core\series.py:1028: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
pandas\core\series.py:1028: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  862M    0  288k    0     0   280k      0  0:52:30  0:00:01  0:52:29  281k
  0  862M    0 4704k    0     0  2393k      0  0:06:09  0:00:01  0:06:08 2396k
  1  862M    1 9952k    0     0  3366k      0  0:04:22  0:00:02  0:04:20 3368k
  1  862M    1 15.1M    0     0  3926k      0  0:03:45  0:00:03  0:03:42 3929k
  2  862M    2 20.8M    0     0  4299k      0  0:03:25  0:00:04  0:03:21 4301k
  3  862M    3 26.4M    0     0  4544k      0  0:03:14  0:00:05  0:03:09 5431k
  3  862M    3 32.3M    0     0  4752k      0  0:03:05  0:00:06  0:02:59 5676k
  4  862M    4 37.0M    0     0  4761k      0  0:03:05  0:00:07  0:02:58 5587k
  4  862M    4 42.5M    0     0  4865k      0  0:03:01  0:00:08  0:02:53 5608k
  5  862M    5 48.4M    0     0  4981k      0  0:02:57  0:00:09  0:02:48 5657k
  6  862M    6 54.0M    0     0  5049k      0  0:02:54  0:00:10  0:02:44 5651k
  6  862M    6 59.5M    0     0  5093k      0  0:02:53  0:00:11  0:02:42 5571k
  7  862M    7 65.2M    0     0  5155k      0  0:02:51  0:00:12  0:02:39 5780k
  8  862M    8 71.2M    0     0  5224k      0  0:02:49  0:00:13  0:02:36 5868k
  8  862M    8 77.4M    0     0  5302k      0  0:02:46  0:00:14  0:02:32 5943k
  9  862M    9 83.5M    0     0  5359k      0  0:02:44  0:00:15  0:02:29 6037k
 10  862M   10 89.5M    0     0  5407k      0  0:02:43  0:00:16  0:02:27 6159k
 11  862M   11 95.4M    0     0  5443k      0  0:02:42  0:00:17  0:02:25 6190k
 11  862M   11  100M    0     0  5453k      0  0:02:42  0:00:18  0:02:24 6091k
 12  862M   12  105M    0     0  5430k      0  0:02:42  0:00:19  0:02:23 5812k
 12  862M   12  110M    0     0  5376k      0  0:02:44  0:00:20  0:02:24 5433k
 13  862M   13  114M    0     0  5333k      0  0:02:45  0:00:21  0:02:24 5082k
 13  862M   13  119M    0     0  5319k      0  0:02:46  0:00:22  0:02:24 4873k
 14  862M   14  123M    0     0  5271k      0  0:02:47  0:00:23  0:02:24 4583k
 14  862M   14  128M    0     0  5290k      0  0:02:47  0:00:24  0:02:23 4731k
 15  862M   15  134M    0     0  5313k      0  0:02:46  0:00:25  0:02:21 5046k
 16  862M   16  139M    0     0  5292k      0  0:02:46  0:00:26  0:02:20 5113k
 16  862M   16  143M    0     0  5255k      0  0:02:48  0:00:27  0:02:21 4966k
 17  862M   17  149M    0     0  5278k      0  0:02:47  0:00:28  0:02:19 5310k
 17  862M   17  154M    0     0  5268k      0  0:02:47  0:00:29  0:02:18 5158k
 18  862M   18  159M    0     0  5260k      0  0:02:47  0:00:30  0:02:17 4985k
 18  862M   18  163M    0     0  5241k      0  0:02:48  0:00:31  0:02:17 4965k
 19  862M   19  169M    0     0  5253k      0  0:02:48  0:00:32  0:02:16 5239k
 20  862M   20  175M    0     0  5289k      0  0:02:47  0:00:33  0:02:14 5350k
 20  862M   20  180M    0     0  5279k      0  0:02:47  0:00:34  0:02:13 5343k
 21  862M   21  184M    0     0  5260k      0  0:02:47  0:00:35  0:02:12 5265k
 21  862M   21  188M    0     0  5233k      0  0:02:48  0:00:36  0:02:12 5180k
 22  862M   22  192M    0     0  5204k      0  0:02:49  0:00:37  0:02:12 4884k
 22  862M   22  197M    0     0  5180k      0  0:02:50  0:00:38  0:02:12 4446k
 23  862M   23  200M    0     0  5143k      0  0:02:51  0:00:39  0:02:12 4190k
 23  862M   23  205M    0     0  5129k      0  0:02:52  0:00:40  0:02:12 4190k
 24  862M   24  208M    0     0  5086k      0  0:02:53  0:00:41  0:02:12 3996k
 24  862M   24  212M    0     0  5053k      0  0:02:54  0:00:42  0:02:12 3903k
 25  862M   25  216M    0     0  5051k      0  0:02:54  0:00:43  0:02:11 4045k
 25  862M   25  221M    0     0  5041k      0  0:02:55  0:00:44  0:02:11 4232k
 26  862M   26  225M    0     0  5021k      0  0:02:55  0:00:45  0:02:10 4134k
 26  862M   26  229M    0     0  5002k      0  0:02:56  0:00:46  0:02:10 4305k
 27  862M   27  233M    0     0  4977k      0  0:02:57  0:00:47  0:02:10 4330k
 27  862M   27  237M    0     0  4969k      0  0:02:57  0:00:48  0:02:09 4249k
 27  862M   27  240M    0     0  4926k      0  0:02:59  0:00:49  0:02:10 3893k
 28  862M   28  243M    0     0  4892k      0  0:03:00  0:00:50  0:02:10 3702k
 28  862M   28  247M    0     0  4877k      0  0:03:01  0:00:51  0:02:10 3696k
 29  862M   29  252M    0     0  4888k      0  0:03:00  0:00:52  0:02:08 4028k
 29  862M   29  258M    0     0  4902k      0  0:03:00  0:00:53  0:02:07 4245k
 30  862M   30  262M    0     0  4896k      0  0:03:00  0:00:54  0:02:06 4595k
 31  862M   31  267M    0     0  4898k      0  0:03:00  0:00:55  0:02:05 4964k
 31  862M   31  272M    0     0  4889k      0  0:03:00  0:00:56  0:02:04 5020k
 31  862M   31  275M    0     0  4874k      0  0:03:01  0:00:57  0:02:04 4729k
 32  862M   32  278M    0     0  4833k      0  0:03:02  0:00:58  0:02:04 4089k
 32  862M   32  280M    0     0  4798k      0  0:03:04  0:00:59  0:02:05 3717k
 32  862M   32  283M    0     0  4765k      0  0:03:05  0:01:00  0:02:05 3276k
 33  862M   33  287M    0     0  4746k      0  0:03:06  0:01:01  0:02:05 3117k
 33  862M   33  290M    0     0  4732k      0  0:03:06  0:01:02  0:02:04 3080k
 34  862M   34  294M    0     0  4714k      0  0:03:07  0:01:03  0:02:04 3301k
 34  862M   34  297M    0     0  4695k      0  0:03:08  0:01:04  0:02:04 3463k
 34  862M   34  301M    0     0  4681k      0  0:03:08  0:01:05  0:02:03 3656k
 35  862M   35  305M    0     0  4664k      0  0:03:09  0:01:06  0:02:03 3646k
 35  862M   35  308M    0     0  4647k      0  0:03:10  0:01:07  0:02:03 3574k
 36  862M   36  312M    0     0  4633k      0  0:03:10  0:01:08  0:02:02 3604k
 36  862M   36  315M    0     0  4622k      0  0:03:11  0:01:09  0:02:02 3668k
 37  862M   37  319M    0     0  4611k      0  0:03:11  0:01:10  0:02:01 3688k
 37  862M   37  323M    0     0  4597k      0  0:03:12  0:01:11  0:02:01 3700k
 37  862M   37  326M    0     0  4581k      0  0:03:12  0:01:12  0:02:00 3692k
 38  862M   38  329M    0     0  4566k      0  0:03:13  0:01:13  0:02:00 3634k
 38  862M   38  333M    0     0  4550k      0  0:03:14  0:01:14  0:02:00 3552k
 39  862M   39  336M    0     0  4538k      0  0:03:14  0:01:15  0:01:59 3497k
 39  862M   39  340M    0     0  4527k      0  0:03:15  0:01:16  0:01:59 3516k
 39  862M   39  344M    0     0  4520k      0  0:03:15  0:01:17  0:01:58 3626k
 40  862M   40  348M    0     0  4514k      0  0:03:15  0:01:18  0:01:57 3745k
 40  862M   40  351M    0     0  4505k      0  0:03:16  0:01:19  0:01:57 3827k
 41  862M   41  355M    0     0  4492k      0  0:03:16  0:01:20  0:01:56 3788k
 41  862M   41  359M    0     0  4486k      0  0:03:16  0:01:21  0:01:55 3847k
 42  862M   42  364M    0     0  4496k      0  0:03:16  0:01:22  0:01:54 4134k
 42  862M   42  368M    0     0  4494k      0  0:03:16  0:01:23  0:01:53 4181k
 43  862M   43  373M    0     0  4498k      0  0:03:16  0:01:24  0:01:52 4383k
 43  862M   43  376M    0     0  4484k      0  0:03:17  0:01:25  0:01:52 4369k
 44  862M   44  380M    0     0  4485k      0  0:03:17  0:01:26  0:01:51 4469k
 44  862M   44  385M    0     0  4491k      0  0:03:16  0:01:27  0:01:49 4399k
 45  862M   45  391M    0     0  4509k      0  0:03:15  0:01:28  0:01:47 4759k
 46  862M   46  397M    0     0  4519k      0  0:03:15  0:01:29  0:01:46 4884k
 46  862M   46  402M    0     0  4528k      0  0:03:15  0:01:30  0:01:45 5278k
 47  862M   47  407M    0     0  4541k      0  0:03:14  0:01:31  0:01:43 5529k
 47  862M   47  413M    0     0  4553k      0  0:03:14  0:01:32  0:01:42 5651k
 48  862M   48  418M    0     0  4562k      0  0:03:13  0:01:33  0:01:40 5517k
 49  862M   49  424M    0     0  4572k      0  0:03:13  0:01:34  0:01:39 5515k
 49  862M   49  429M    0     0  4583k      0  0:03:12  0:01:35  0:01:37 5588k
 50  862M   50  434M    0     0  4586k      0  0:03:12  0:01:36  0:01:36 5398k
 50  862M   50  439M    0     0  4589k      0  0:03:12  0:01:37  0:01:35 5244k
 51  862M   51  444M    0     0  4595k      0  0:03:12  0:01:38  0:01:34 5205k
 52  862M   52  449M    0     0  4607k      0  0:03:11  0:01:39  0:01:32 5272k
 52  862M   52  454M    0     0  4611k      0  0:03:11  0:01:40  0:01:31 5153k
 53  862M   53  459M    0     0  4614k      0  0:03:11  0:01:41  0:01:30 5163k
 53  862M   53  464M    0     0  4623k      0  0:03:11  0:01:42  0:01:29 5287k
 54  862M   54  470M    0     0  4635k      0  0:03:10  0:01:43  0:01:27 5428k
 55  862M   55  476M    0     0  4647k      0  0:03:10  0:01:44  0:01:26 5447k
 55  862M   55  481M    0     0  4656k      0  0:03:09  0:01:45  0:01:24 5554k
 56  862M   56  487M    0     0  4665k      0  0:03:09  0:01:46  0:01:23 5706k
 57  862M   57  492M    0     0  4668k      0  0:03:09  0:01:47  0:01:22 5612k
 57  862M   57  497M    0     0  4675k      0  0:03:08  0:01:48  0:01:20 5513k
 58  862M   58  502M    0     0  4682k      0  0:03:08  0:01:49  0:01:19 5421k
 58  862M   58  508M    0     0  4694k      0  0:03:08  0:01:50  0:01:18 5493k
 59  862M   59  513M    0     0  4699k      0  0:03:08  0:01:51  0:01:17 5424k
 60  862M   60  519M    0     0  4711k      0  0:03:07  0:01:52  0:01:15 5622k
 60  862M   60  525M    0     0  4721k      0  0:03:07  0:01:53  0:01:14 5732k
 61  862M   61  530M    0     0  4726k      0  0:03:06  0:01:54  0:01:12 5698k
 62  862M   62  535M    0     0  4732k      0  0:03:06  0:01:55  0:01:11 5587k
 62  862M   62  541M    0     0  4741k      0  0:03:06  0:01:56  0:01:10 5692k
 63  862M   63  547M    0     0  4748k      0  0:03:06  0:01:57  0:01:09 5582k
 63  862M   63  552M    0     0  4753k      0  0:03:05  0:01:58  0:01:07 5470k
 64  862M   64  558M    0     0  4764k      0  0:03:05  0:01:59  0:01:06 5633k
 65  862M   65  564M    0     0  4774k      0  0:03:05  0:02:00  0:01:05 5753k
 66  862M   66  569M    0     0  4783k      0  0:03:04  0:02:01  0:01:03 5750k
 66  862M   66  575M    0     0  4791k      0  0:03:04  0:02:02  0:01:02 5817k
 67  862M   67  580M    0     0  4797k      0  0:03:04  0:02:03  0:01:01 5853k
 67  862M   67  586M    0     0  4803k      0  0:03:03  0:02:04  0:00:59 5734k
 68  862M   68  592M    0     0  4813k      0  0:03:03  0:02:05  0:00:58 5738k
 69  862M   69  597M    0     0  4819k      0  0:03:03  0:02:06  0:00:57 5709k
 69  862M   69  602M    0     0  4820k      0  0:03:03  0:02:07  0:00:56 5536k
 70  862M   70  607M    0     0  4827k      0  0:03:03  0:02:08  0:00:55 5558k
 71  862M   71  612M    0     0  4828k      0  0:03:03  0:02:09  0:00:54 5453k
 71  862M   71  618M    0     0  4833k      0  0:03:02  0:02:10  0:00:52 5340k
 72  862M   72  623M    0     0  4839k      0  0:03:02  0:02:11  0:00:51 5332k
 72  862M   72  629M    0     0  4847k      0  0:03:02  0:02:12  0:00:50 5544k
 73  862M   73  635M    0     0  4854k      0  0:03:02  0:02:13  0:00:49 5553k
 74  862M   74  641M    0     0  4863k      0  0:03:01  0:02:14  0:00:47 5789k
 74  862M   74  646M    0     0  4871k      0  0:03:01  0:02:15  0:00:46 5868k
 75  862M   75  652M    0     0  4877k      0  0:03:01  0:02:16  0:00:45 5900k
 76  862M   76  658M    0     0  4885k      0  0:03:00  0:02:17  0:00:43 5877k
 76  862M   76  664M    0     0  4895k      0  0:03:00  0:02:18  0:00:42 5984k
 77  862M   77  670M    0     0  4903k      0  0:03:00  0:02:19  0:00:41 5974k
 78  862M   78  675M    0     0  4907k      0  0:03:00  0:02:20  0:00:40 5876k
 78  862M   78  680M    0     0  4908k      0  0:03:00  0:02:21  0:00:39 5736k
 79  862M   79  685M    0     0  4912k      0  0:02:59  0:02:22  0:00:37 5665k
 80  862M   80  690M    0     0  4913k      0  0:02:59  0:02:23  0:00:36 5430k
 80  862M   80  695M    0     0  4913k      0  0:02:59  0:02:24  0:00:35 5180k
 81  862M   81  699M    0     0  4910k      0  0:02:59  0:02:25  0:00:34 5003k
 81  862M   81  703M    0     0  4899k      0  0:03:00  0:02:26  0:00:34 4664k
 82  862M   82  707M    0     0  4897k      0  0:03:00  0:02:27  0:00:33 4473k
 82  862M   82  712M    0     0  4897k      0  0:03:00  0:02:28  0:00:32 4417k
 83  862M   83  717M    0     0  4896k      0  0:03:00  0:02:29  0:00:31 4426k
 83  862M   83  721M    0     0  4891k      0  0:03:00  0:02:30  0:00:30 4339k
 83  862M   83  724M    0     0  4882k      0  0:03:00  0:02:31  0:00:29 4357k
 84  862M   84  727M    0     0  4873k      0  0:03:01  0:02:32  0:00:29 4161k
 84  862M   84  731M    0     0  4867k      0  0:03:01  0:02:33  0:00:28 3991k
 85  862M   85  736M    0     0  4868k      0  0:03:01  0:02:34  0:00:27 4027k
 85  862M   85  741M    0     0  4868k      0  0:03:01  0:02:35  0:00:26 4189k
 86  862M   86  746M    0     0  4867k      0  0:03:01  0:02:36  0:00:25 4412k
 86  862M   86  748M    0     0  4854k      0  0:03:02  0:02:37  0:00:25 4278k
 87  862M   87  751M    0     0  4842k      0  0:03:02  0:02:38  0:00:24 4070k
 87  862M   87  756M    0     0  4839k      0  0:03:02  0:02:39  0:00:23 3927k
 88  862M   88  761M    0     0  4844k      0  0:03:02  0:02:40  0:00:22 4079k
 88  862M   88  766M    0     0  4847k      0  0:03:02  0:02:41  0:00:21 4238k
 89  862M   89  773M    0     0  4858k      0  0:03:01  0:02:42  0:00:19 4981k
 90  862M   90  779M    0     0  4871k      0  0:03:01  0:02:43  0:00:18 5793k
 91  862M   91  786M    0     0  4879k      0  0:03:01  0:02:44  0:00:17 6191k
 91  862M   91  792M    0     0  4890k      0  0:03:00  0:02:45  0:00:15 6371k
 92  862M   92  799M    0     0  4903k      0  0:03:00  0:02:46  0:00:14 6692k
 93  862M   93  805M    0     0  4913k      0  0:02:59  0:02:47  0:00:12 6706k
 94  862M   94  812M    0     0  4925k      0  0:02:59  0:02:48  0:00:11 6699k
 94  862M   94  818M    0     0  4933k      0  0:02:59  0:02:49  0:00:10 6694k
 95  862M   95  823M    0     0  4933k      0  0:02:59  0:02:50  0:00:09 6374k
 95  862M   95  828M    0     0  4931k      0  0:02:59  0:02:51  0:00:08 5879k
 96  862M   96  832M    0     0  4925k      0  0:02:59  0:02:52  0:00:07 5335k
 96  862M   96  836M    0     0  4926k      0  0:02:59  0:02:53  0:00:06 4956k
 97  862M   97  840M    0     0  4922k      0  0:02:59  0:02:54  0:00:05 4536k
 98  862M   98  846M    0     0  4925k      0  0:02:59  0:02:55  0:00:04 4656k
 98  862M   98  851M    0     0  4928k      0  0:02:59  0:02:56  0:00:03 4846k
 99  862M   99  857M    0     0  4932k      0  0:02:59  0:02:57  0:00:02 5145k
 99  862M   99  862M    0     0  4935k      0  0:02:59  0:02:58  0:00:01 5269k
100  862M  100  862M    0     0  4936k      0  0:02:59  0:02:59 --:--:-- 5544k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  219M    0  224k    0     0   186k      0  0:20:10  0:00:01  0:20:09  186k
  2  219M    2 4912k    0     0  2280k      0  0:01:38  0:00:02  0:01:36 2282k
  4  219M    4 10.8M    0     0  3535k      0  0:01:03  0:00:03  0:01:00 3538k
  7  219M    7 16.5M    0     0  4067k      0  0:00:55  0:00:04  0:00:51 4069k
  9  219M    9 21.6M    0     0  4294k      0  0:00:52  0:00:05  0:00:47 4425k
 12  219M   12 26.7M    0     0  4446k      0  0:00:50  0:00:06  0:00:44 5483k
 14  219M   14 32.8M    0     0  4697k      0  0:00:47  0:00:07  0:00:40 5737k
 17  219M   17 38.0M    0     0  4774k      0  0:00:47  0:00:08  0:00:39 5555k
 19  219M   19 41.9M    0     0  4696k      0  0:00:47  0:00:09  0:00:38 5219k
 21  219M   21 46.8M    0     0  4728k      0  0:00:47  0:00:10  0:00:37 5175k
 23  219M   23 51.9M    0     0  4767k      0  0:00:47  0:00:11  0:00:36 5163k
 26  219M   26 58.0M    0     0  4890k      0  0:00:46  0:00:12  0:00:34 5166k
 28  219M   28 63.6M    0     0  4953k      0  0:00:45  0:00:13  0:00:32 5245k
 31  219M   31 68.9M    0     0  4986k      0  0:00:45  0:00:14  0:00:31 5517k
 33  219M   33 73.2M    0     0  4948k      0  0:00:45  0:00:15  0:00:30 5395k
 35  219M   35 79.0M    0     0  5012k      0  0:00:44  0:00:16  0:00:28 5558k
 37  219M   37 83.5M    0     0  4986k      0  0:00:45  0:00:17  0:00:28 5220k
 40  219M   40 89.2M    0     0  5035k      0  0:00:44  0:00:18  0:00:26 5251k
 42  219M   42 94.5M    0     0  5054k      0  0:00:44  0:00:19  0:00:25 5247k
 45  219M   45  100M    0     0  5084k      0  0:00:44  0:00:20  0:00:24 5497k
 47  219M   47  104M    0     0  5049k      0  0:00:44  0:00:21  0:00:23 5170k
 49  219M   49  109M    0     0  5056k      0  0:00:44  0:00:22  0:00:22 5297k
 52  219M   52  114M    0     0  5065k      0  0:00:44  0:00:23  0:00:21 5172k
 54  219M   54  119M    0     0  5076k      0  0:00:44  0:00:24  0:00:20 5160k
 56  219M   56  125M    0     0  5101k      0  0:00:44  0:00:25  0:00:19 5170k
 59  219M   59  130M    0     0  5100k      0  0:00:44  0:00:26  0:00:18 5314k
 61  219M   61  135M    0     0  5110k      0  0:00:44  0:00:27  0:00:17 5347k
 63  219M   63  140M    0     0  5106k      0  0:00:44  0:00:28  0:00:16 5298k
 66  219M   66  145M    0     0  5105k      0  0:00:44  0:00:29  0:00:15 5246k
 68  219M   68  150M    0     0  5100k      0  0:00:44  0:00:30  0:00:14 5098k
 70  219M   70  155M    0     0  5107k      0  0:00:44  0:00:31  0:00:13 5147k
 72  219M   72  159M    0     0  5090k      0  0:00:44  0:00:32  0:00:12 4985k
 74  219M   74  163M    0     0  5060k      0  0:00:44  0:00:33  0:00:11 4801k
 76  219M   76  168M    0     0  5045k      0  0:00:44  0:00:34  0:00:10 4694k
 78  219M   78  172M    0     0  5028k      0  0:00:44  0:00:35  0:00:09 4592k
 80  219M   80  177M    0     0  5038k      0  0:00:44  0:00:36  0:00:08 4608k
 82  219M   82  182M    0     0  5029k      0  0:00:44  0:00:37  0:00:07 4632k
 85  219M   85  187M    0     0  5042k      0  0:00:44  0:00:38  0:00:06 4919k
 87  219M   87  191M    0     0  5018k      0  0:00:44  0:00:39  0:00:05 4835k
 89  219M   89  197M    0     0  5023k      0  0:00:44  0:00:40  0:00:04 4987k
 92  219M   92  202M    0     0  5035k      0  0:00:44  0:00:41  0:00:03 5014k
 94  219M   94  207M    0     0  5049k      0  0:00:44  0:00:42  0:00:02 5196k
 97  219M   97  213M    0     0  5066k      0  0:00:44  0:00:43  0:00:01 5250k
 98  219M   98  217M    0     0  5036k      0  0:00:44  0:00:44 --:--:-- 5178k
100  219M  100  219M    0     0  5014k      0  0:00:44  0:00:44 --:--:-- 4941k
pandas\core\frame.py:10169: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
pandas\core\frame.py:10169: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
pandas\core\internals\blocks.py:366: RuntimeWarning: invalid value encountered in log10
scipy\stats\_stats_py.py:197: RuntimeWarning: invalid value encountered in log

**Comment by j-berg** [comment]
Hi - thanks for reaching out! Can you check your input data files for any weird symbols of "inf" values or the like? It sounds like it is running into an issue where a log is trying to be applied to a 0 or a non-real number. If you would like, I can also take a look at the data (email: jordanberg.contact@gmail.com)

**Comment by yeast1234** [comment]
Thanks for your support.  It was a formatting issue and I solved it.

**Comment by j-berg** [comment]
Great, going to close this issue for now but feel free to reopen if you run into similar issues!
