### ISSUE TITLE
spawn python ENOENT on Windows installation

### ISSUE THREAD

**Issue by pr2tik1** [Metaboverse/Metaboverse#160]
**Describe the bug**
An error message pops up during launch stating following error : 

![Screenshot 2024-04-11 at 4 00 56 PM](https://github.com/Metaboverse/Metaboverse/assets/34391513/fdb1bd07-2f83-4ad1-a22e-9dc1fab08028)

**To Reproduce**
1. Installation on windows
2. Launch

**Expected behavior**
App launch shouldn't expect such behaviour.

**Screenshots**
If possible, please screenshot the Developer logs which can be found at `View` -> `Toggle Developer Tools` -> `Console` to help us address the bug easier.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : NA
 - Version : [Metaboverse-v0.11.2](https://github.com/Metaboverse/Metaboverse/releases/tag/v0.11.2) [Latest](https://github.com/Metaboverse/Metaboverse/releases/latest)

**Additional context**

**Comment by j-berg** [comment]
Hi - thanks for identifying this issue. It seems like this error is arising from a block of code that is no longer necessary, so I've removed it from the code base and will be fixed in v0.11.3.
