### ISSUE TITLE
Is there a plan to broaden the range of species or make the curation part open?

### ISSUE THREAD

**Issue by kkami1115** [Metaboverse/Metaboverse#22]
I really appreciate the appearance of tool for large-scale multi-omics analysis, but there are no plants among the supported species.

Is there any plans to add biological networks of plants in the future, or for more general use, to public the principle and code for curation so that users can create their biological networks of the species they want to use?
(It would be great to be able to upload user-created biological networks to the Metaboverse server, like WikiPathways!)
It doesn't have to be a high priority, but I think function like this may be necessary for the future.

Anyway, I am very grateful for the development of this tool. I hope you keep up the good work and continue to develop.

**Comment by j-berg** [comment]
Hi @kkami1115, thanks for your interest in Metaboverse! Sorry the curation part isn't clear, I probably need to add a note to the README that specifies the component parts of the software better. You can find the codebase for the underlying curation [here](https://github.com/Metaboverse/metaboverse-cli). I package the Python backend using Pyinstaller and directly include the binary in the main Metaboverse app, but all the code used to create that backend binary is open-source at the URL above. 

The underlying curation depends on a couple of different file types from Reactome. If there are similar files available for the plant of interest, I think the code would be adaptable to curating a plant species, and I think would be a valuable contribution to the Metaboverse environment.
1. Pathway-based SMBL files with all reactions and components of reactions (see [this archive](https://reactome.org/download/current/all_species.3.1.sbml.tgz)). This also includes information through the `hasPart` tags for protein complexes
2. A gene to reactome ID reference (see [this file](https://reactome.org/download/current/Ensembl2Reactome_PE_All_Levels.txt))
3. A protein to reactome ID reference (see [this file](https://reactome.org/download/current/UniProt2Reactome_PE_All_Levels.txt))
4. Protein complex information (see [this file](ftp://ftp.ebi.ac.uk/pub/databases/chebi/Flat_file_tab_delimited/names.tsv.gz) and [this file](https://hmdb.ca/system/downloads/current/hmdb_metabolites.zip)) -- this may be more broadly applicable across organisms than just human

To do: `Add component code descriptions to Metaboverse README page`

Feel free to add any other requests of features you would like to see!

**Comment by kkami1115** [comment]
I wondered for a moment if the information in KEGG, rather than from Reactome, could replace the above, but the granularity of information is different between Reactome and KEGG, so it doesn't seem to be able to be applied directly.
Since KEGG has no protein information, is it possible to create a similar network from transcript data and metabolite data only?

**Comment by j-berg** [comment]
I think it should be tractable to use KEGG annotations, I think the only caveat would be that Metaboverse is based on a reaction-centric representation of metabolism. Do you have a public link to their curation files? For some reason, I was under the impression that that was under a paywall of sorts.
