### ISSUE TITLE
Metaboverse unable to interface with local paths for users without admin mode

### ISSUE THREAD

**Issue by j-berg** [Metaboverse/Metaboverse#27]
**Describe the bug**
If a user is using Metaboverse on a non-admin account, Metaboverse is unable to download files to that computer.

**To Reproduce**
1. Curate in non-admin mode

**Expected behavior**
Able to download and interface on admin or non-admin accounts

**Screenshots**
<img width="673" alt="Screen Shot 2020-06-29 at 8 46 37 AM (2)" src="https://user-images.githubusercontent.com/27102119/86024049-ba292a80-b9e9-11ea-9684-e4fde6d70fc5.png">

**Desktop (please complete the following information):**
 - Seems to be Windows-specific but may apply to other OSs
 - Metaboverse v0.1.2b

**Additional context**
Add a way to allow Metaboverse to run in non-admin mode and download as a non-admin user would use

Try these resources for ideas:
- https://github.com/atom/atom/issues/2860
- https://github.com/electron-userland/electron-builder/issues/4474
- https://medium.com/@github.gkarthiks/how-to-install-nodejs-and-npm-in-non-admin-access-windows-machines-102fd461b54c

**Comment by j-berg** [comment]
Looks like the issue arising from the Python backend trying to call cURL, but not sure yet if this is a OS-independent issue or Windows-specific

**Comment by guillermoturiel** [comment]
Hi, I still get this error while running Metaboverse on admin mode. 

![image](https://user-images.githubusercontent.com/57098120/86104085-df876880-babd-11ea-8874-d9cd1ff87e51.png)

**Comment by j-berg** [comment]
Hi @guillermoturiel, I think the error you are getting is because of spaces in a folder name. This was fixed in #25 and will be released in `v0.1.3b` later today or tomorrow. Thanks for your patience!

**Comment by guillermoturiel** [comment]
Hi @j-berg thanks for your answer. Removing spaces in the folder name seems to work but now I am getting this error. I get this using my own data and also with the data of the walkthrough video you uploaded. 

![image](https://user-images.githubusercontent.com/57098120/86214058-ee802080-bb7a-11ea-8aeb-2f4c981db989.png)

**Comment by j-berg** [comment]
Hi @guillermoturiel , this may be related to an issue we are currently addressing that appears to be affecting file paths on Windows OS. I am hoping to have the fix finalized later today and will keep you updated.

To make sure I am diagnosing this correctly, could you please send me the Developer Tool logs, which can be found at: 
`View` -> `Toggle Developer Tools` -> `Console`

For this particular issue, you may need to expand the output for one of the logs and scroll to the bottom to find the last error that the system hit. Thanks!

**Comment by j-berg** [comment]
Changes will be included in `v0.1.3b`

**Comment by j-berg** [comment]
Changes discussed above implemented and appear to be stable. Closing, but please reopen the issue if you continue to have issues.
