### ISSUE TITLE
Error when building network model

### ISSUE THREAD

**Issue by Metuser** [Metaboverse/Metaboverse#30]
**Describe the bug:**
Error pop-up immediately appears when trying to build network. Tried uploading both txt and tsv files in the input format described, and tried editing sample names etc.

**Screenshots:**
![image](https://user-images.githubusercontent.com/67636490/86119648-36209100-bb16-11ea-8401-7ee6ce226b48.png)

**Desktop:**
MacOS v.0.1.2b

**Comment by j-berg** [comment]
Hi @Metuser could you take a screenshot with the Developer Tools Console open? 

Developer logs which can be found at `View` -> `Toggle Developer Tools` -> `Console`

**Comment by j-berg** [comment]
Closing stale issue. Starting in [v0.1.4b](https://github.com/Metaboverse/Metaboverse/releases/tag/Metaboverse-v0.1.4b), users will be provided with an error log file in their specified output folder that can be submitted with their issue to allow for more comprehensive troubleshooting. If using v0.1.4b or greater, and the error persists, please re-open the issue or open a new issue. Thanks!
