### ISSUE TITLE
Walkthrough video

### ISSUE THREAD

**Issue by j-berg** [Metaboverse/Metaboverse#31]
Update walkthrough video for clarity

Some items on the to-do list:
- Add captions 
- Document different motifs better, explain in video what each does and how to interpret and use them

**Comment by zhou325** [comment]
- Add a summary of the functionalities at the beginning of the video before going through details.
- Delete some unnecessary clips, for example, the clip around 8:30 - 8:50, which is just to reload the network.
- In the "Visualize" part, should we also explain the meanings of the shadings in the graph? I'm not sure if the compartments are straightforward to our users or not.

**Comment by j-berg** [comment]
Addressed by:
https://github.com/Metaboverse/Metaboverse/commit/f3af4a285afda0e187df8ae21d7d4779208d8c42
https://github.com/Metaboverse/Metaboverse/commit/c50ad739e722696d809c698984f7b53e15630c86
https://github.com/Metaboverse/Metaboverse/commit/b4bece0deb5b508e5e8875246acaca123821bc80
https://github.com/Metaboverse/Metaboverse/commit/501691cc00b4688acd45fbbc2666ced3df2097d5
https://github.com/Metaboverse/Metaboverse/commit/5e9ba5369f7bb6ff1b84411d4a76b234c91dc213

New video at https://youtu.be/U7m78Tbs5KE
