### ISSUE TITLE
pattern analysis

### ISSUE THREAD

**Issue by neococo** [Metaboverse/Metaboverse#36]
I am just getting started, but I wanted to add a suggestion for future consideration. In an experiment such as a timecourse, it would be useful to be able to see the pattern of change of a given metabolite (or gene in RNAseq data for that matter) over time. If such patterns could be clustered, that can aid in determining the mechanism of action of the perturbation in question. I know there are a few approaches for doing this with transcriptomic data in R, but you have a much nicer GUI. 

Best,
Mike

**Comment by kkami1115** [comment]
I'm interested in that too, but I have one thing to consider.
We can assume that patterns of gene expressions will be similar between genes with similar functions, but that's not the case with metabolites.
(Or rather, this is my past experience.)
So, I think applying clustering to metabolites is a bad idea.
However, to visualize each gene/metabolite data(in any type; A-B, multi conditions, time-series) is great leap for more user-friendly tool, I'd like to see that feature added.

**Comment by j-berg** [comment]
Hi @neococo, I like the idea, but I also agree that @kkami1115's suggestion that the methods used for RNA-seq clustering may differ and not be appropriate for metabolite data. However, we do have plans to incorporate two features that get at what was suggested that you might be interested in (see #15 and #16). I think I will close this issue and add you both to those issues so we can discuss those there if you like and you can track their progress (feel free to remove yourself from the issues if you would prefer). Thanks!
