### ISSUE TITLE
Include Trypanosoma database

### ISSUE THREAD

**Issue by SaraivaFMS** [Metaboverse/Metaboverse#57]
I'm working on Trypanosoma cruzi (CL Brener) metabolism and have quantitative transcriptomic and metabolomic that I'd like to usein Metaboverse. But searching on Metaboverse I realized that T. cruzi is still not included as a searchable organism. I tryed to load a database file but it didn't work. Is there a way to include T. cruzi database in the future? Also, are there a way to load an database for an organism that is not included in the search list?
Thanks

**Comment by j-berg** [comment]
Do you know how close the metabolism and gene/protein nomenclature is between *T. cruzi* and *Trypanosoma brucei*? I have plans to incorporate the ability to use curations from the [BioModels database](https://www.ebi.ac.uk/biomodels/BMID000000141814) in the near future (see issue #56), and I'm wondering if this would work or if you have a different metabolism curation in mind? What was the database file you tried loading?

**Comment by SaraivaFMS** [comment]
Thanks for the answer. The metabolism of Trypanosoma cruzi and Trypanosoma brucei are quite close but it has relevant differences. I don't know if it is possible to use this anotation (http://bigg.ucsd.edu/models/iIS312). I had difficult to get a file with an "pickle" extension. Most of genome banks don't have this files for download.

**Comment by j-berg** [comment]
The `.pickle` files associated with Metaboverse are custom database files, so those won't show up in other sources. Looking at the available files from this resource, it looks like the provided `.xml` files will work. I will have to modify some of the back-end curation process in Metaboverse, but this should be pretty straightforward to address while I address issue #56. I will update you here once this is finished.

**Comment by j-berg** [comment]
Hi @SaraivaFMS -- I have a draft version working for BiGG models. Could you provide me with some test -omics data so I can make sure data is being mapped to the network correctly? If you have RNA-seq, proteomics, and metabolomics data, that would be great, but if you just have one or two of those, that would be perfectly fine as well. Thanks!

**Comment by j-berg** [comment]
Addressed by:
https://github.com/Metaboverse/Metaboverse/commit/7b1c2f2a91c26bbda02d56448e6da75e2aa28f5f
https://github.com/Metaboverse/Metaboverse/commit/d7bfd512c77b78f6ca4f2f82e04ed9af597c95a3
https://github.com/Metaboverse/Metaboverse/commit/af273224e10f490e225601c65668c18771c7d841
https://github.com/Metaboverse/metaboverse-cli/commit/2d4965d3aa6fbe4b4bc54d9d00754bb4c5f72d22
https://github.com/Metaboverse/metaboverse-cli/commit/46083fbaf89c29e262096e03229e9890e26154c3
https://github.com/Metaboverse/metaboverse-cli/commit/a24fa2899e45d529a3ce28944f2bc4729c15773f
https://github.com/Metaboverse/metaboverse-cli/commit/9bfe243e7d4ed8a62081d434dda0068acbada614
https://github.com/Metaboverse/metaboverse-cli/commit/4bba83c274fd396dacc80c7c57af6fcdc96c8ef7
https://github.com/Metaboverse/metaboverse-cli/commit/d238fca92a07a5094fbf7951a4d6db27912ade70

To Do:
- [ ] Testing

**Comment by j-berg** [comment]
Hi @SaraivaFMS -- I just wanted to try to touch base again and see if you had any datasets you could share to make sure the new database functionalities are operating as expected. I plan on trying to try to tackle wrapping this up after the holidays. Thanks and happy holidays!

**Comment by j-berg** [comment]
Hi, just wanted to check in again on this -- if you have a example dataset, you can include it here (you will probably need to be in GitHub to do this) or email me at jordan.berg <at> biochem.utah.edu

**Comment by j-berg** [comment]
See/watch https://github.com/Metaboverse/Metaboverse/issues/73 for summary details.

Integration and testing is complete for a variety of BiGG and BioModels networks, however users should do some spot checking as the available models are not as uniform as Reactome models between organisms. 

Updated capabilities should be released in the next few days with `v0.6.0`
