### ISSUE TITLE
Mapping metabolites using ChEBIs

### ISSUE THREAD

**Issue by mguharoy** [Metaboverse/Metaboverse#58]
Hi!

I am trying to overlay (human) metabolomics data onto the Metaboverse created network. However, metabolite ChEBI ids are not being recognised, and the "unmapped" (output) text file basically returns back all the input metabolites. However, I made sure that the input ChEBI ids are all present in Reactome.

There were no errors while creating the network. I am attaching the output (unmapped) metabolomics data file here. It is a multi-condition experiment as shown by the corresponding labels. The input file was a tsv file with the same data, but couldn't upload the tsv file here. Is there any obvious mistake in the input, format-wise, etc.?

thanks for your help!
[targetedMetabolites_byChEBIs_rawAbundances_bySystem_unmapped.txt](https://github.com/Metaboverse/Metaboverse/files/5530135/targetedMetabolites_byChEBIs_rawAbundances_bySystem_unmapped.txt)

**Comment by j-berg** [comment]
Hi! Sorry you are running into issues, and thank you for reaching out. This is certainly odd. Thank you for providing the example data. I am attending a virtual conference this week, but should be able to dig into this early next week to see what is going on, and will keep you updated on my progress.

Thanks for your interest in using Metaboverse!

**Comment by mguharoy** [comment]
Hi Jordan, I'm looking forward to your feedback on this potential issue. Thanks!

**Comment by j-berg** [comment]
Hi @mguharoy -- I think I tracked down the issue. You could check out this file in [`v0.3.0b`](https://github.com/Metaboverse/Metaboverse/releases/tag/Metaboverse-v0.3.0b) to see if what you expect to be mapping based on CHEBI ID is in fact doing so. I looked at the networks before and after these changes using the `Metabolism -> Creatine Metabolism` pathway, and it looked like metabolites that hadn't been mapping before are doing so now. I will continue to stress test this and make sure things are stable and include the updated mapping in `v0.4.0b`. I expect to have that released in the next 1-2 weeks once I finalize some other changes that are scheduled for `v0.4.0b`. Let me know if you notice anything strange or anything else that should be addressed. Thanks!!

**Comment by j-berg** [comment]
Addressed in: https://github.com/Metaboverse/metaboverse-cli/commit/3e656da51d64158e69c5f08dec0668e5cba4fcc1
To-do: 
- [ ] Testing

**Comment by mguharoy** [comment]
Hi Jordan, I tested the json file you sent, everything seems ok in terms of metabolite mapping. I will continue to take a look. And importantly, I look forward to using the CHEBI mapping functionality in v0.4.0b.
Thanks,
Mainak Guharoy.

**Comment by j-berg** [comment]
Tests and corrections to initial code added in:
https://github.com/Metaboverse/metaboverse-cli/commit/18e026d9a33de91db304096a31be0028e1f94279
https://github.com/Metaboverse/metaboverse-cli/commit/a304afd8e284afcea08c7157f71c778ac1f68a41

Bumped additions to be included in `v0.3.1b`, slated for release by 2020-12-06 -- @mguharoy, you should be able to access these changes by Monday at the latest. Let me know if you run into any issues in using the update. Thanks again for reaching out!
