### ISSUE TITLE
error running metaboverse

### ISSUE THREAD

**Issue by MTOBIO** [Metaboverse/Metaboverse#63]
Hi there,

This is my first time using Metaboverse, I have close-to-zero experience with programming and am semi-illiterate in computer stuff (it's good to get that out of my chest!). I think this is a very important tool for the field and I appreciate your efforts to put this to work!

I tried running Metaboverse this morning with transcriptomic and metabolomic data, but the I got an error message few seconds after I hit the submission button. All my input files look ok, but I did have some trouble installing the 0.3.2b version of the program yesterday (don't know why, but everything looked ok after I restarted my computer).

I'd really appreciate some help here. Attached you'll find the metaboverse_session.log file and a screenshot of the console.

Best,

Marcos.

<img width="529" alt="image" src="https://user-images.githubusercontent.com/75793063/101785301-5bf58d00-3adb-11eb-83fd-760277b186ba.png">
[metaboverse_session.log](https://github.com/Metaboverse/Metaboverse/files/5673428/metaboverse_session.log)

**Comment by j-berg** [comment]
Hi Marcos,

Thanks for your interest in Metaboverse and thanks for reaching out! And thanks for sending both the log and the screenshot, this is very helpful. I think what is currently going on is the backend is having trouble parsing a special character in one of the options. I think this is just a problem with how I am passing the user data to the backend. I will work on sorting this out the next couple of days and hope to have an update (as `v0.3.3b`) out by Monday.

Let me know if you have any other questions or run into any other issues.

Thanks!
Jordan

**Comment by MTOBIO** [comment]
Thank you, Jordan!
I also noticed an error message every time I close Metaboverse. I´m not sure this is related to the problem I told before, but I though it was important to tell you. You can see the screenshot below.


Have a good weekend,
Marcos.


    Em quinta-feira, 10 de dezembro de 2020 12:15:36 BRT, Jordan Berg <notifications@github.com> escreveu:  
 
 


Hi Marcos,

Thanks for your interest in Metaboverse and thanks for reaching out! And thanks for sending both the log and the screenshot, this is very helpful. I think what is currently going on is the backend is having trouble parsing a special character in one of the options. I think this is just a problem with how I am passing the user data to the backend. I will work on sorting this out the next couple of days and hope to have an update (as v0.3.3b) out by Monday.

Let me know if you have any other questions or run into any other issues.

Thanks!
Jordan

**Comment by j-berg** [comment]
Hi Marcos,

Unfortunately, the screenshot did not attach. You may need to post it directly on GitHub and not through email. 
If you are working on a mac, I have seen this as well on this OS. It doesn't seem to affect anything as long as Metaboverse is fully quit (sometimes you will have to force quit the app). I hope to eventually fix this issue.

Thanks!
Jordan

**Comment by j-berg** [comment]
Hi Marcos,

I was unable to directly replicate the error you received, but think I may understand the issue and have found a solution. Would you mind trying [this linked version](https://github.com/j-berg/j-berg/releases/download/Metaboverse-darwin-x64-0.3.3a/Metaboverse-darwin-x64-0.3.3a.zip) of Metaboverse with all the same inputs you provided last time and let me know if it works or if you receive another error? If there is an error, could you attach the log file again? You will probably get an error message telling you you are not using the most recent version, but you can just ignore that.

Thanks!
Jordan

**Comment by MTOBIO** [comment]
Yes, I´ll certainly do that! I´ll let you know as soon as I have some time today.
Thanks,
Marcos.

    Em domingo, 13 de dezembro de 2020 17:59:22 BRT, Jordan Berg <notifications@github.com> escreveu:  
 
 


Hi Marcos,

I was unable to directly replicate the error you received, but think I may understand the issue and have found a solution. Would you mind trying this linked version of Metaboverse with all the same inputs you provided last time and let me know if it works or if you receive another error? If there is an error, could you attach the log file again? You will probably get an error message telling you you are not using the most recent version, but you can just ignore that.

Thanks!
Jordan

**Comment by MTOBIO** [comment]
All right, I just tried it again and I got the error message again. Attached you will find the log file and the screenshot from the console.
Please let me know if I can be of any help. I can´t do much "computationally", but I can run all the necessary tests to help you out.
Best,
Marcos.
    Em segunda-feira, 14 de dezembro de 2020 09:13:46 BRT, Marcos Tulio de Oliveira <mtobio@yahoo.com.br> escreveu:  
 
  Yes, I´ll certainly do that! I´ll let you know as soon as I have some time today.
Thanks,
Marcos.

    Em domingo, 13 de dezembro de 2020 17:59:22 BRT, Jordan Berg <notifications@github.com> escreveu:  
 
 


Hi Marcos,

I was unable to directly replicate the error you received, but think I may understand the issue and have found a solution. Would you mind trying this linked version of Metaboverse with all the same inputs you provided last time and let me know if it works or if you receive another error? If there is an error, could you attach the log file again? You will probably get an error message telling you you are not using the most recent version, but you can just ignore that.

Thanks!
Jordan

**Comment by j-berg** [comment]
Hi Marcos,

Could you try uploading the files directly on GitHub? Unfortunately, I don't know if they get attached correctly when using email.

Thanks!
Jordan

**Comment by MTOBIO** [comment]
My bad! You did mention this before, but I simply forgot...

Let's see if it will work now!

Best,

Marcos.
[Doc1.docx](https://github.com/Metaboverse/Metaboverse/files/5690549/Doc1.docx)
[metaboverse_session.log](https://github.com/Metaboverse/Metaboverse/files/5690554/metaboverse_session.log)

**Comment by j-berg** [comment]
No worries, got it, thanks!! Sorry there is still an issue, thanks for your patience as we go back and forth! Could you try [this version](https://github.com/j-berg/j-berg/releases/download/Metaboverse-darwin-x64-0.3.3a/Metaboverse-darwin-x64-0.3.3a.zip) when you have a moment?

**Comment by MTOBIO** [comment]
Hi Jordan,
It worked! Thank you. Now I need to learn how to interpret the data... It´s a lot!
I´ll let you know if I have any other problems. For now, I just wanna wish happy holidays!
Best,
Marcos.

    Em segunda-feira, 14 de dezembro de 2020 17:31:48 BRT, Jordan Berg <notifications@github.com> escreveu:  
 
 


No worries, got it, thanks!! Sorry there is still an issue, thanks for your patience as we go back and forth! Could you try this version when you have a moment?

**Comment by j-berg** [comment]
That's great news! Thanks for the update -- I will release the official 0.3.3b sometime today, but it will be exactly what you have now. Just want to put a release on the actual Metaboverse release page with this change. I will close this issue once those changes are finalized.

Let me know if you run into any further issues or if you have any questions as you go through your analysis, best of luck and happy holidays!

**Comment by j-berg** [comment]
Sorry for the delay on my end -- [`v0.3.3b`](https://github.com/Metaboverse/Metaboverse/releases/tag/Metaboverse-v0.3.3b) is live. Let me know if you run into similar or new issues, thanks for you help in addressing this issue!
