### ISSUE TITLE
Problem to open .mvrs file after analysis

### ISSUE THREAD

**Issue by khaleddz1995** [Metaboverse/Metaboverse#92]
Hi everyone, I am currently trying to analyze my transcriptomics with Metaboverse. At the end of the analysis, completed to 100%, I always receive this error message (see picture). I don't know what is the problem with this. 

![image](https://user-images.githubusercontent.com/85108699/120209575-24b49d00-c22f-11eb-90a0-e1169fb9a191.png)
Thanks a lot
Khaled

**Comment by j-berg** [comment]
Hi @khaleddz1995,

Thanks for letting us know you are running into this issue, and sorry you're running into this issue!

Did you receive a `metaboverse_session.log` file output at your specified output location (`...\Desktop\Metaboverse-win32-x64-0.7.0\metaboverse\`). Or do you see a `test3.mvrs` file output at that location? 

If you received the log file, could you upload that here to help us diagnose the issue? If you see a `.mvrs` file output, does it load into the Metaboverse home page where there is the option to load a previous database?

If neither of these files appeared in your output location, you could also try selecting the output location to be just your Desktop? It's less likely, but it could be that it is getting hung up on trying to output other files into the Metaboverse software folder.

**Comment by khaleddz1995** [comment]
Dear j-berg , thanks a lot for your answer. 

I did not receive any metaboverse_session.log file, but yes I had a file named test3.mvrs in my output location. When I try to open it through metaboverse.exe home page, I have this message  (see picture), even after putting the file (test3.mvrs) on the desktop.

![image](https://user-images.githubusercontent.com/85108699/120212782-b245bc00-c232-11eb-879f-1b30f6c4416b.png)

**Comment by j-berg** [comment]
Hmm, strange. Would you be okay loading the `.mvrs` file here and I can take a closer look. If there is data involved that you don't want public, feel free to email me jordan.berg<at>biochem.utah.edu

**Comment by khaleddz1995** [comment]
Hi j-berg, no problem. I sent you by mail the file

**Comment by j-berg** [comment]
Cause was the usage of commas instead of decimals in input values. Changed to allow flexible input styles, where commas will be replaced by decimals for user inputs.

Addressed by:
- https://github.com/Metaboverse/metaboverse-cli/commit/e0a1257416da24995c0b5667df7b7a0b79dc30a9
- https://github.com/Metaboverse/metaboverse-cli/commit/3c48be5ea8f699b4dd22785b0ba8f0ba34094b6e

Will run some final tests and changes will be included in next release of Metaboverse
