### ISSUE TITLE
Calculation algorithm

### ISSUE THREAD

**Issue by Lilongjian** [Metaboverse/Metaboverse#98]
Hello, did you use any other plug-ins for the calculation method of model generation
![image](https://user-images.githubusercontent.com/34147554/127292037-1532602b-0ab7-4b01-86bd-168fa6416798.png)

**Comment by j-berg** [comment]
Hi @Lilongjian ,

Could you clarify what part of the processing you are referring to? Are you talking about the progress counter specifically, or related to how Metaboverse is actually generating the model? 

Regarding the progress counter, Metaboverse has a progress internal file that it uses to communicate with the backend, where the backend updates that progress file after each step of the modeling. The front-end uses a watcher function that looks for changes to this progress file and updates the progress bar any time it sees a change. 

Is this the error you are running into? It looks like there is no progress bar showing up for you? Do you receive an error log file to your specified output location?

**Comment by Lilongjian** [comment]
how Metaboverse is actually generating the model

**Comment by j-berg** [comment]
I see. Metaboverse is generating the model by parsing out Reactome pathway-level files for reaction-level information (reaction inputs, outputs, modifiers). Each reaction and reaction component is added to the NetworkX-formatted graph as a node and each reaction-component connection is added as an edge. 

Metaboverse also uses a variety of reference files from ChEBI, UniProt, etc. to help map user data onto the network.

Does this help answer your question?

**Comment by Lilongjian** [comment]
![image](https://user-images.githubusercontent.com/34147554/127586077-c6f8f61e-d66e-43d0-8647-4a55dff91649.png)
Hi@j-berg,
The place circled by the red box in the picture.How are those files generated.

**Comment by j-berg** [comment]
The backend that performed the network curation I mentioned in the previous response is handled by [metaboverse-cli](https://github.com/Metaboverse/metaboverse-cli). The executables for [metaboverse-cli](https://github.com/Metaboverse/metaboverse-cli) are packaged by [PyInstaller](https://www.pyinstaller.org/) and included with each compiled version of Metaboverse. [PyInstaller](https://www.pyinstaller.org/) also has the advantage of packaging any other Python dependencies needed for the executable, so the [metaboverse-cli](https://github.com/Metaboverse/metaboverse-cli) executable is able to be a stand-alone program without needing to handle installation of any other dependencies when running the program.

**Comment by Lilongjian** [comment]
thanks

**Comment by j-berg** [comment]
Great, I'll close this issue for now but feel free to re-open if you have any other questions!

Thanks!
