### ISSUE TITLE
Operational problems

### ISSUE THREAD

**Issue by Lilongjian** [Metaboverse/Metaboverse#99]
![image](https://user-images.githubusercontent.com/34147554/129133003-ad3ddbc6-bbec-49ec-b04a-e5847f2978d0.png)

Metaboverse: error while loading shared libraries: libatk-bridge-2.0.so.0: cannot open shared object file: No such file or directory

**Comment by j-berg** [comment]
Could you provide me with some more information about your operating system and provide the session log file?

> Generally, for any errors occurring during network building, a file named `metaboverse_session.log` will be output to your specified Output folder.

**Comment by Lilongjian** [comment]
Thank you.
How to start metaboverse on Linux system？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Metaboverse/Metaboverse"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月12日(星期四) 晚上11:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Metaboverse/Metaboverse] Operational problems (#99)





 
Could you provide me with some more information about your operating system and provide the session log file?
  
Generally, for any errors occurring during network building, a file named metaboverse_session.log will be output to your specified Output folder.
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by j-berg** [comment]
Are you able to start Metaboverse using [these instructions](https://metaboverse.readthedocs.io/en/latest/content/installation.html#permissions-notices)? Also, if you are able to run Metaboverse and you are running into issues when building a network, do you get a `metaboverse_session.log` at the output location you specified?

**Comment by Lilongjian** [comment]
Can I access it in the browser？

**Comment by j-berg** [comment]
Hi, sorry for the slow response. I have been out of town the last few weeks and I am catching up on messages. Metaboverse is not accessible in the browser. It uses Electron, which serves a Desktop app within a Chromium-like browser, but is not directly accessed from the web.
